- name: Check if db_password secret exists
  command: docker secret inspect db_password
  register: db_password_check
  failed_when: false
  changed_when: false

- name: Create db_password secret
  shell: openssl rand -base64 32 | tr -d '\n' | docker secret create db_password -
  when: db_password_check.rc != 0

- name: Check if secret_key secret exists
  command: docker secret inspect secret_key
  register: secret_key_check
  failed_when: false
  changed_when: false

- name: Create secret_key secret
  shell: openssl rand -base64 50 | tr -d '\n' | docker secret create secret_key -
  when: secret_key_check.rc != 0
