# Generated by Django 6.0.2 on 2026-02-25 15:15

import django.db.models.deletion
from django.db import migrations, models


def create_help_user_and_wiki(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.create(
        username="help",
        email="help@localhost",
        is_active=False,
    )

    HelpWiki = apps.get_model("help", "HelpWiki")
    HelpWiki.objects.create()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('wikis', '0002_create_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpWiki',
            fields=[
                ('wiki_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikis.wiki')),
            ],
            options={
                'verbose_name': 'help wiki',
            },
            bases=('wikis.wiki',),
        ),
        migrations.RunPython(create_help_user_and_wiki),
    ]
