from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path, reverse_lazy
from django.views.generic import RedirectView

from campaigns.views import (
    CampaignCreateView,
    CampaignDeleteView,
    CampaignJoinView,
    CampaignLeaveView,
    CampaignListView,
    CampaignNotebooksView,
    CampaignSettingsView,
    CampaignView,
    CampaignWikiPageCreateView,
    CampaignWikiPageView,
    CampaignWikiView,
)
from help.views import HelpPageView
from notebooks.views import (
    NotebookCollaboratorsView,
    NotebookCreateView,
    NotebookDeletedPagesView,
    NotebookDeleteView,
    NotebookIndexView,
    NotebookListView,
    NotebookPageCreateView,
    NotebookPageDeleteView,
    NotebookPageRestoreView,
    NotebookPageView,
    NotebookRenameView,
    NotebookSettingsView,
    NotebookUploadView,
    NotebookUserListView,
    NotebookVisibilityView,
)
from users.views import (
    PasswordChangeView,
    ProfileLinksView,
    ProfileRedirectView,
    ProfileTokensView,
    ProfileView,
    ProfileVisibilityView,
    UserLoginView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="/login")),

    path(
        route="login",
        name="login",
        view=UserLoginView.as_view(),
    ),
    path(
        route="logout",
        name="logout",
        view=LogoutView.as_view(next_page="/"),
    ),

    re_path(
        route=r"^help/(?P<path>.*)$",
        name="help",
        view=HelpPageView.as_view(),
    ),

    path(
        route="profile/",
        name="profile_redirect",
        view=ProfileRedirectView.as_view(),
    ),
    path(
        route="profile/<str:username>/",
        name="profile",
        view=ProfileView.as_view(),
    ),
    path(
        route="profile/<str:username>/links",
        name="profile_links",
        view=ProfileLinksView.as_view(),
    ),
    path(
        route="profile/<str:username>/visibility",
        name="profile_visibility",
        view=ProfileVisibilityView.as_view(),
    ),
    path(
        route="profile/<str:username>/password",
        name="password_change",
        view=PasswordChangeView.as_view(),
    ),
    path(
        route="profile/<str:username>/tokens",
        name="profile_tokens",
        view=ProfileTokensView.as_view(),
    ),

    path(
        route="campaigns/",
        name="campaign_list",
        view=CampaignListView.as_view(),
    ),
    path(
        route="campaigns/<str:username>/",
        view=RedirectView.as_view(url=reverse_lazy("campaign_list"), permanent=False),
    ),
    path(
        route="campaigns/create",
        name="campaign_create",
        view=CampaignCreateView.as_view(),
    ),
    path(
        route="campaigns/join-<str:join_slug>",
        name="campaign_join",
        view=CampaignJoinView.as_view(),
    ),
    path(
        route="campaigns/delete",
        name="campaign_delete",
        view=CampaignDeleteView.as_view(),
    ),
    path(
        route="campaigns/leave",
        name="campaign_leave",
        view=CampaignLeaveView.as_view(),
    ),
    path(
        route="campaigns/notebooks",
        name="campaign_notebooks",
        view=CampaignNotebooksView.as_view(),
    ),
    path(
        route="campaigns/settings/<str:username>/<str:slug>",
        name="campaign_settings",
        view=CampaignSettingsView.as_view(),
    ),
    path(
        route="campaigns/<str:username>/<str:slug>/",
        name="campaign",
        view=CampaignView.as_view(),
    ),
    path(
        route="campaigns/<str:username>/<str:slug>/create-page",
        name="campaign_wiki_create_page",
        view=CampaignWikiPageCreateView.as_view(),
    ),
    path(
        route="campaigns/<str:username>/<str:slug>/wiki/",
        name="campaign_wiki",
        view=CampaignWikiView.as_view(),
    ),
    path(
        route="campaigns/<str:username>/<str:slug>/wiki/<path:path>/",
        name="campaign_wiki_directory",
        view=CampaignWikiView.as_view(),
    ),
    path(
        route="campaigns/<str:username>/<str:slug>/wiki/<path:path>",
        name="campaign_wiki_page",
        view=CampaignWikiPageView.as_view(),
    ),

    path(
        route="notebooks/",
        name="notebook_list",
        view=NotebookListView.as_view(),
    ),
    path(
        route="notebooks/<str:username>/",
        name="notebook_user_list",
        view=NotebookUserListView.as_view(),
    ),
    path(
        route="notebooks/create",
        name="notebook_create",
        view=NotebookCreateView.as_view(),
    ),
    path(
        route="notebooks/rename",
        name="notebook_rename",
        view=NotebookRenameView.as_view(),
    ),
    path(
        route="notebooks/visibility",
        name="notebook_visibility",
        view=NotebookVisibilityView.as_view(),
    ),
    path(
        route="notebooks/collaborators",
        name="notebook_collaborators",
        view=NotebookCollaboratorsView.as_view(),
    ),
    path(
        route="notebooks/upload",
        name="notebook_upload",
        view=NotebookUploadView.as_view(),
    ),
    path(
        route="notebooks/delete",
        name="notebook_delete",
        view=NotebookDeleteView.as_view(),
    ),
    path(
        route="notebooks/delete-page",
        name="notebook_delete_page",
        view=NotebookPageDeleteView.as_view(),
    ),
    path(
        route="notebooks/restore",
        name="notebook_restore",
        view=NotebookPageRestoreView.as_view(),
    ),
    path(
        route="notebooks/settings/<str:username>/<str:slug>/",
        name="notebook_settings",
        view=NotebookSettingsView.as_view(),
    ),
    path(
        route="notebooks/deleted/<str:username>/<str:slug>/",
        name="notebook_deleted",
        view=NotebookDeletedPagesView.as_view(),
    ),
    path(
        route="notebooks/create-page/<str:username>/<str:slug>/",
        name="notebook_create_page",
        view=NotebookPageCreateView.as_view(),
    ),
    path(
        route="notebooks/<str:username>/<str:slug>/",
        name="notebook",
        view=NotebookIndexView.as_view(),
    ),
    path(
        route="notebooks/<str:username>/<str:slug>/<path:path>/",
        name="notebook_directory",
        view=NotebookIndexView.as_view(),
    ),
    path(
        route="notebooks/<str:username>/<str:slug>/<path:path>",
        name="notebook_page",
        view=NotebookPageView.as_view(),
    ),
]
