#!/usr/bin/env -S bash -euo pipefail

# Extract tested state helper functions from sync-notebook.sh
# for use by setup_helpers.sh in other test files.

source tests/sync-notebook.sh

{
    echo "# Auto-generated by extract-state-helpers.sh"
    echo "# Do not edit directly."
    echo "# noqa file"
    echo ""
    echo "# shellcheck shell=bash"
    echo "declare state_file remote_state_file"
    echo ""
    declare -f update_sync_state
    echo ""
    declare -f get_sync_state
    echo ""
    declare -f update_remote_state
    echo ""
    declare -f get_remote_state
} > tests/state-helpers.sh
