# Generated by Django 6.0.3 on 2026-03-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_rename_users_to_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('internal', 'Internal'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
