# Generated by Django 6.0.3 on 2026-04-01 05:23

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_permissions(apps, schema_editor):
    NotebookPermission = apps.get_model("notebooks", "NotebookPermission")
    seen = set()
    for perm in NotebookPermission.objects.order_by("id"):
        key = (perm.notebook_id, perm.user_id)
        if key in seen:
            perm.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_add_campaign_notebook_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_permissions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='notebookpermission',
            constraint=models.UniqueConstraint(fields=('notebook', 'user'), name='unique_notebook_user'),
        ),
    ]
