# Generated by Django 6.0.2 on 2026-02-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikis', '0001_wiki_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-number']},
        ),
    ]
