# Generated by Django 6.0.2 on 2026-02-26 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikis', '0002_create_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
