# Generated by Django 6.0.2 on 2026-03-13 09:27

import django.db.models.deletion
import notebooks.models
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebooks', '0001_create_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('join_slug', models.CharField(max_length=32, unique=True)),
                ('owner', models.ForeignKey(on_delete=models.SET(users.models.get_sentinel_user), related_name='owned_campaigns', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(notebooks.models.OwnedSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CampaignNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notebooks', to='campaigns.campaign')),
                ('linked_by', models.ForeignKey(on_delete=models.SET(users.models.get_sentinel_user), related_name='linked_notebooks', to=settings.AUTH_USER_MODEL)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notebooks', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_campaign_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='campaignnotebook',
            constraint=models.UniqueConstraint(fields=('campaign', 'notebook'), name='unique_notebook_per_campaign'),
        ),
    ]
