# Generated by Django 6.0.3 on 2026-03-31 13:44

from django.db import migrations, models
from slugify import slugify


def generate_unique_slug(Notebook, name, owner):
    base_slug = slugify(name)
    slug = base_slug
    counter = 2
    while Notebook.objects.filter(slug=slug, owner=owner).exists():
        slug = f"{base_slug}-{counter}"
        counter += 1
    return slug


def create_wiki_notebooks(apps, schema_editor):
    Campaign = apps.get_model('campaigns', 'Campaign')
    CampaignNotebook = apps.get_model('campaigns', 'CampaignNotebook')
    Notebook = apps.get_model('notebooks', 'Notebook')
    NotebookPermission = apps.get_model('notebooks', 'NotebookPermission')

    for campaign in Campaign.objects.all():
        if CampaignNotebook.objects.filter(campaign=campaign, is_wiki=True).exists():
            continue
        name = f"{campaign.name} wiki"
        notebook = Notebook.objects.create(
            name=name,
            slug=generate_unique_slug(Notebook, name, campaign.owner),
            owner=campaign.owner,
            visibility='private',
        )
        CampaignNotebook.objects.filter(campaign=campaign).update(
            order=models.F('order') + 1
        )
        CampaignNotebook.objects.create(
            campaign=campaign,
            notebook=notebook,
            linked_by=campaign.owner,
            order=0,
            is_wiki=True,
        )
        for player in campaign.players.exclude(pk=campaign.owner_id):
            NotebookPermission.objects.create(
                notebook=notebook,
                user=player,
                role='editor',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_create_campaign'),
        ('notebooks', '0001_create_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignnotebook',
            name='is_wiki',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_wiki_notebooks, migrations.RunPython.noop),
    ]
