# Generated by Django 6.0.3 on 2026-03-31 15:15

from django.conf import settings
from django.db import migrations, models


def populate_slugs(apps, schema_editor):
    CampaignNotebook = apps.get_model("campaigns", "CampaignNotebook")
    for link in CampaignNotebook.objects.filter(is_wiki=False):
        link.slug = link.notebook.slug
        link.save()


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_add_wiki_notebook'),
        ('notebooks', '0004_add_campaign_notebook_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignnotebook',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='campaignnotebook',
            constraint=models.UniqueConstraint(fields=('campaign', 'slug'), name='unique_slug_per_campaign'),
        ),
    ]
